### PR TITLE
Fix blank quote

### PR DESCRIPTION
**Pull request by yyYiran**
image
fixed: 
- blank quote
- login screen margin
- each post attach to current user

### CODE REVIEW

**Comment by yyYiran** [comment]
image

**Comment by yyYiran** [comment]
image
Back button so that user don't have to scroll to buttom to go back

**Review by DavidWangwjh — APPROVED** [review]
Everything works!

**Comment by DavidWangwjh** [comment]
conflicts in DetailPostActivity resolved manually

**Pull request merged**
