### PR TITLE
Implement "Quote of the day"

### LINKED ISSUE #20: Implement: get quote of the day
- [x] https://gist.github.com/awran5/355643af99164a61ae0f95c84206d151
- [x] make this an **asset** json file, copy and past
- [x] parse, random, to get quote of the day
- [x] display in suggestionActivity

### PR DESCRIPTION
**Pull request by angelinale1104**
Here is the demo:

### CODE REVIEW

**Review by yyYiran — APPROVED** [review]
Works! Looking amazing! Minor fox might be needed when quote is too long, but we can do that later. 
image

**Review by yyYiran — COMMENTED** [review]
image
I've got some issues in Suggestion Activity tho

**Comment by yyYiran** [comment]
> image
> 
> I've got some issues in Suggestion Activity tho

worked after adding this line to build.gradle
`implementation 'com.android.volley:volley:1.2.1'`

**Comment by angelinale1104** [comment]
> Works! Looking amazing! Minor fox might be needed when quote is too long, but we can do that later. image

Yeah we can fix this for sure! Maybe in the next milestone

**Comment by angelinale1104** [comment]
> > image
> > I've got some issues in Suggestion Activity tho
> 
> worked after adding this line to build.gradle `implementation 'com.android.volley:volley:1.2.1'`

Also, I thought I already added that in the build.gradle file? Hmm that is weird. But at least it works on your end now :)

**Pull request merged**
